# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tfpose_ros/Person.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tfpose_ros.msg

class Person(genpy.Message):
  _md5sum = "77159240dfbac2f3737aaebf05ff898d"
  _type = "tfpose_ros/Person"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """BodyPartElm[] body_part
================================================================================
MSG: tfpose_ros/BodyPartElm
uint32 part_id
float32 x
float32 y
float32 confidence"""
  __slots__ = ['body_part']
  _slot_types = ['tfpose_ros/BodyPartElm[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       body_part

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Person, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.body_part is None:
        self.body_part = []
    else:
      self.body_part = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.body_part)
      buff.write(_struct_I.pack(length))
      for val1 in self.body_part:
        _x = val1
        buff.write(_get_struct_I3f().pack(_x.part_id, _x.x, _x.y, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.body_part is None:
        self.body_part = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.body_part = []
      for i in range(0, length):
        val1 = tfpose_ros.msg.BodyPartElm()
        _x = val1
        start = end
        end += 16
        (_x.part_id, _x.x, _x.y, _x.confidence,) = _get_struct_I3f().unpack(str[start:end])
        self.body_part.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.body_part)
      buff.write(_struct_I.pack(length))
      for val1 in self.body_part:
        _x = val1
        buff.write(_get_struct_I3f().pack(_x.part_id, _x.x, _x.y, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.body_part is None:
        self.body_part = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.body_part = []
      for i in range(0, length):
        val1 = tfpose_ros.msg.BodyPartElm()
        _x = val1
        start = end
        end += 16
        (_x.part_id, _x.x, _x.y, _x.confidence,) = _get_struct_I3f().unpack(str[start:end])
        self.body_part.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I3f = None
def _get_struct_I3f():
    global _struct_I3f
    if _struct_I3f is None:
        _struct_I3f = struct.Struct("<I3f")
    return _struct_I3f
