// Generated by gencpp from file approaching/ApproachInfo.msg
// DO NOT EDIT!


#ifndef APPROACHING_MESSAGE_APPROACHINFO_H
#define APPROACHING_MESSAGE_APPROACHINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <approaching/Coord.h>

namespace approaching
{
template <class ContainerAllocator>
struct ApproachInfo_
{
  typedef ApproachInfo_<ContainerAllocator> Type;

  ApproachInfo_()
    : ids()
    , coords()
    , dists()  {
    }
  ApproachInfo_(const ContainerAllocator& _alloc)
    : ids(_alloc)
    , coords(_alloc)
    , dists(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _ids_type;
  _ids_type ids;

   typedef std::vector< ::approaching::Coord_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::approaching::Coord_<ContainerAllocator> >::other >  _coords_type;
  _coords_type coords;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dists_type;
  _dists_type dists;





  typedef boost::shared_ptr< ::approaching::ApproachInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::approaching::ApproachInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ApproachInfo_

typedef ::approaching::ApproachInfo_<std::allocator<void> > ApproachInfo;

typedef boost::shared_ptr< ::approaching::ApproachInfo > ApproachInfoPtr;
typedef boost::shared_ptr< ::approaching::ApproachInfo const> ApproachInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::approaching::ApproachInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::approaching::ApproachInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace approaching

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'approaching': ['/home/vision/work/computer_vision_projects/catkin_ws/src/approaching/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::approaching::ApproachInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::approaching::ApproachInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::approaching::ApproachInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::approaching::ApproachInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::approaching::ApproachInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::approaching::ApproachInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::approaching::ApproachInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6fccf8aff213da9b738fdf6be5c98c4";
  }

  static const char* value(const ::approaching::ApproachInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6fccf8aff213da9ULL;
  static const uint64_t static_value2 = 0xb738fdf6be5c98c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::approaching::ApproachInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "approaching/ApproachInfo";
  }

  static const char* value(const ::approaching::ApproachInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::approaching::ApproachInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] ids\n\
Coord[] coords\n\
float32[] dists\n\
\n\
================================================================================\n\
MSG: approaching/Coord\n\
int16 x\n\
int16 y\n\
";
  }

  static const char* value(const ::approaching::ApproachInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::approaching::ApproachInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
      stream.next(m.coords);
      stream.next(m.dists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApproachInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::approaching::ApproachInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::approaching::ApproachInfo_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "coords[]" << std::endl;
    for (size_t i = 0; i < v.coords.size(); ++i)
    {
      s << indent << "  coords[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::approaching::Coord_<ContainerAllocator> >::stream(s, indent + "    ", v.coords[i]);
    }
    s << indent << "dists[]" << std::endl;
    for (size_t i = 0; i < v.dists.size(); ++i)
    {
      s << indent << "  dists[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dists[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APPROACHING_MESSAGE_APPROACHINFO_H
