// Generated by gencpp from file smelling_detection/Rectangle.msg
// DO NOT EDIT!


#ifndef SMELLING_DETECTION_MESSAGE_RECTANGLE_H
#define SMELLING_DETECTION_MESSAGE_RECTANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smelling_detection
{
template <class ContainerAllocator>
struct Rectangle_
{
  typedef Rectangle_<ContainerAllocator> Type;

  Rectangle_()
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
    }
  Rectangle_(const ContainerAllocator& _alloc)
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
  (void)_alloc;
    }



   typedef int16_t _x1_type;
  _x1_type x1;

   typedef int16_t _y1_type;
  _y1_type y1;

   typedef int16_t _x2_type;
  _x2_type x2;

   typedef int16_t _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::smelling_detection::Rectangle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smelling_detection::Rectangle_<ContainerAllocator> const> ConstPtr;

}; // struct Rectangle_

typedef ::smelling_detection::Rectangle_<std::allocator<void> > Rectangle;

typedef boost::shared_ptr< ::smelling_detection::Rectangle > RectanglePtr;
typedef boost::shared_ptr< ::smelling_detection::Rectangle const> RectangleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smelling_detection::Rectangle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smelling_detection::Rectangle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace smelling_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'smelling_detection': ['/home/vision/work/computer_vision_projects/catkin_ws/src/smelling_detection/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::smelling_detection::Rectangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smelling_detection::Rectangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smelling_detection::Rectangle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smelling_detection::Rectangle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smelling_detection::Rectangle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smelling_detection::Rectangle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smelling_detection::Rectangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "941a022bd67bae4c5b403bdabd31e17c";
  }

  static const char* value(const ::smelling_detection::Rectangle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x941a022bd67bae4cULL;
  static const uint64_t static_value2 = 0x5b403bdabd31e17cULL;
};

template<class ContainerAllocator>
struct DataType< ::smelling_detection::Rectangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smelling_detection/Rectangle";
  }

  static const char* value(const ::smelling_detection::Rectangle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smelling_detection::Rectangle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x1\n\
int16 y1\n\
int16 x2\n\
int16 y2\n\
";
  }

  static const char* value(const ::smelling_detection::Rectangle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smelling_detection::Rectangle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rectangle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smelling_detection::Rectangle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smelling_detection::Rectangle_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMELLING_DETECTION_MESSAGE_RECTANGLE_H
