# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from head_pose_estimation/GazingInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import head_pose_estimation.msg

class GazingInfo(genpy.Message):
  _md5sum = "ab56e55ea0d34f912262cded1f939fc7"
  _type = "head_pose_estimation/GazingInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool[] is_gazing
Coord2D[] coords

================================================================================
MSG: head_pose_estimation/Coord2D
int16 x
int16 y
"""
  __slots__ = ['is_gazing','coords']
  _slot_types = ['bool[]','head_pose_estimation/Coord2D[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_gazing,coords

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GazingInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.is_gazing is None:
        self.is_gazing = []
      if self.coords is None:
        self.coords = []
    else:
      self.is_gazing = []
      self.coords = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.is_gazing)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.is_gazing))
      length = len(self.coords)
      buff.write(_struct_I.pack(length))
      for val1 in self.coords:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.coords is None:
        self.coords = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.is_gazing = struct.unpack(pattern, str[start:end])
      self.is_gazing = map(bool, self.is_gazing)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.coords = []
      for i in range(0, length):
        val1 = head_pose_estimation.msg.Coord2D()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.coords.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.is_gazing)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.is_gazing.tostring())
      length = len(self.coords)
      buff.write(_struct_I.pack(length))
      for val1 in self.coords:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.coords is None:
        self.coords = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.is_gazing = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.is_gazing = map(bool, self.is_gazing)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.coords = []
      for i in range(0, length):
        val1 = head_pose_estimation.msg.Coord2D()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.coords.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
