// Generated by gencpp from file head_pose_estimation/GazingInfo.msg
// DO NOT EDIT!


#ifndef HEAD_POSE_ESTIMATION_MESSAGE_GAZINGINFO_H
#define HEAD_POSE_ESTIMATION_MESSAGE_GAZINGINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <head_pose_estimation/Coord2D.h>

namespace head_pose_estimation
{
template <class ContainerAllocator>
struct GazingInfo_
{
  typedef GazingInfo_<ContainerAllocator> Type;

  GazingInfo_()
    : is_gazing()
    , coords()  {
    }
  GazingInfo_(const ContainerAllocator& _alloc)
    : is_gazing(_alloc)
    , coords(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _is_gazing_type;
  _is_gazing_type is_gazing;

   typedef std::vector< ::head_pose_estimation::Coord2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::head_pose_estimation::Coord2D_<ContainerAllocator> >::other >  _coords_type;
  _coords_type coords;





  typedef boost::shared_ptr< ::head_pose_estimation::GazingInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_pose_estimation::GazingInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GazingInfo_

typedef ::head_pose_estimation::GazingInfo_<std::allocator<void> > GazingInfo;

typedef boost::shared_ptr< ::head_pose_estimation::GazingInfo > GazingInfoPtr;
typedef boost::shared_ptr< ::head_pose_estimation::GazingInfo const> GazingInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_pose_estimation::GazingInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace head_pose_estimation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'head_pose_estimation': ['/home/vision/work/computer_vision_projects/catkin_ws/src/head_pose_estimation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_pose_estimation::GazingInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pose_estimation::GazingInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pose_estimation::GazingInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab56e55ea0d34f912262cded1f939fc7";
  }

  static const char* value(const ::head_pose_estimation::GazingInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab56e55ea0d34f91ULL;
  static const uint64_t static_value2 = 0x2262cded1f939fc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_pose_estimation/GazingInfo";
  }

  static const char* value(const ::head_pose_estimation::GazingInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] is_gazing\n\
Coord2D[] coords\n\
\n\
================================================================================\n\
MSG: head_pose_estimation/Coord2D\n\
int16 x\n\
int16 y\n\
";
  }

  static const char* value(const ::head_pose_estimation::GazingInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_gazing);
      stream.next(m.coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazingInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_pose_estimation::GazingInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_pose_estimation::GazingInfo_<ContainerAllocator>& v)
  {
    s << indent << "is_gazing[]" << std::endl;
    for (size_t i = 0; i < v.is_gazing.size(); ++i)
    {
      s << indent << "  is_gazing[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.is_gazing[i]);
    }
    s << indent << "coords[]" << std::endl;
    for (size_t i = 0; i < v.coords.size(); ++i)
    {
      s << indent << "  coords[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::head_pose_estimation::Coord2D_<ContainerAllocator> >::stream(s, indent + "    ", v.coords[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_POSE_ESTIMATION_MESSAGE_GAZINGINFO_H
